adb_path: adb
clear_tutorial_on_load: true
disable_maxes: false
force_lang_game_data: false
game_data_repo: https://git.battlecatsmodding.org/fieryhenry/BCData/raw/branch/main/metadata.json
ignore_parse_error: true
locale: en
max_backups: 50
max_request_timeout: 30
remove_ban_message_on_load: true
reset_cat_data: true
separate_cat_edit_options: true
set_cat_current_forms: true
show_missing_locale_keys: false
show_update_message: true
strict_ban_prevention: false
strict_upgrade: false
theme: default
unlock_cat_on_edit: true
update_to_beta: false
use_file_dialog: true
use_pkexec_waydroid: true
use_waydroid: false
