FROM ubuntu:24.04@sha256:c4a8d5503dfb2a3eb8ab5f807da5bc69a85730fb49b5cfca2330194ebcc41c7b

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        socat \
        qemu-system-misc \
        bash && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN useradd -m -s /bin/bash user

COPY mkfs kernel /home/user/
COPY user/ /home/user/user/
COPY chall.sh /home/user/chall.sh
COPY flag.txt /home/user/flag.txt
RUN chmod +x /home/user/chall.sh /home/user/mkfs

USER user
WORKDIR /home/user

EXPOSE 1337

CMD socat -T 60 TCP-LISTEN:1337,reuseaddr,fork,max-children=32 EXEC:/home/user/chall.sh,stderr
