version: '3.8'

services:
  challenge:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: debug_container
    ports:
      - "5000:5000" # port for socat
    stdin_open: true
    tty: true
    cap_add:
      - SYS_PTRACE
